name: Test API

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx
        
    - name: Test API Health Check
      run: |
        python -c "
        from main import app
        from fastapi.testclient import TestClient
        
        client = TestClient(app)
        response = client.get('/health')
        assert response.status_code == 200
        print('Health check passed!')
        "
        
    - name: Test API Documentation
      run: |
        python -c "
        from main import app
        from fastapi.testclient import TestClient
        
        client = TestClient(app)
        response = client.get('/docs')
        assert response.status_code == 200
        print('API docs accessible!')
        "